Name        : AFDAL ZIKRI ALFALIH

Matrix      : 24211243

Department  : Artificial Intelligence

In [ ]:
import numpy as np
# 1. Create a numpy array of size 2x2
array_2x2 = np.array([[1,2],[3,4]])
print(array_2x2)

[[1 2]
 [3 4]]


In [ ]:
# 2. Create a random numpy array of size 3x4
random_3x4 = np.random.rand(3,4)
print(random_3x4)

[[0.25593667 0.7614006  0.88292885 0.64933533]
 [0.14765411 0.98814662 0.50877134 0.20184114]
 [0.84893435 0.93370993 0.62688737 0.64356219]]


In [ ]:
# 3. Create a numpy array of ones and a numpy array of zeros
ones_array = np.ones((2,3))
zeros_array = np.zeros((2,3))
print(ones_array)
print()
print(zeros_array)

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 4. Create a random numpy array of size 6x3 and transpose it
random_6x3 = np.random.rand(6,3)
transpose_array = random_6x3.T
print(random_6x3)
print()
print(transpose_array)

[[0.9623453  0.18604247 0.59846944]
 [0.61382386 0.73325648 0.09830155]
 [0.00952128 0.24054291 0.22702452]
 [0.10696158 0.49494388 0.07164494]
 [0.64617315 0.39967358 0.96862558]
 [0.20582601 0.07073196 0.68710899]]

[[0.9623453  0.61382386 0.00952128 0.10696158 0.64617315 0.20582601]
 [0.18604247 0.73325648 0.24054291 0.49494388 0.39967358 0.07073196]
 [0.59846944 0.09830155 0.22702452 0.07164494 0.96862558 0.68710899]]


In [ ]:
# 5. Create two random numpy array of size n x p and p x m and then compute the dot product
n, p, m = 3, 2, 4
A = np.random.rand(n,p)
B = np.random.rand(p,m)
dot_product = np.dot(A,B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("dot product :\n", dot_product)

Matrix A:
 [[0.61040705 0.43974604]
 [0.34603561 0.38003737]
 [0.3883498  0.88441384]]
Matrix B:
 [[0.12646955 0.01351142 0.64218416 0.72788026]
 [0.66681941 0.3762344  0.17664912 0.89329084]]
dot product :
 [[0.3704291  0.17369505 0.46967449 0.83712436]
 [0.29717927 0.14765857 0.28935186 0.5913564 ]
 [0.63885874 0.33799407 0.40562302 1.07271094]]
